# Generated by Django 3.0.8 on 2020-07-22 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='name',
            new_name='nombre',
        ),
    ]
